name: movie
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  alice: ^0.2.5
  another_flushbar: ^1.10.24
  logger: ^1.1.0
  equatable: ^2.0.3
  device_info_plus: ^3.1.1
  intl: ^0.17.0
  flutter_screenutil: ^5.0.0+2
  flutter_svg: ^1.0.3
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  hydrated_bloc: ^8.1.0
  cached_network_image: ^3.2.0
  collection: ^1.15.0
  dartz: ^0.10.0
  dio: ^4.0.0
  get_it: ^7.2.0
  package_info: ^2.0.2
  path_provider: ^2.0.9
#  shared_preferences: ^2.0.8
  url_launcher: ^6.0.12
  google_fonts: ^2.1.0
  pretty_dio_logger: ^1.1.1
  flutter_launcher_icons: ^0.9.2
  flutter_spinkit: ^5.1.0
  smooth_page_indicator: ^1.0.0+2
  flutter_rating_bar: ^4.0.1
  youtube_player_iframe: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
